server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;

    location / {
        return 200 'Hello from HTTPS - Suraj DevOps!';
        add_header Content-Type text/plain;
    }
}

server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}
